[package]
name = "skeld"
version = "0.3.0-dev"
edition = "2021"

authors = ["hacrvlq <hacrvlq@proton.me"]
description = "a tui tool for opening projects in a restricted sandbox to prevent supply chain attacks such as typesquatting"
keywords = ["sandbox", "security", "project", "tui", "terminal-interface"]
categories = ["command-line-interface"]
readme = ".github/README.md"
repository = "https://github.com/hacrvlq/skeld"
license = "MIT"

[dependencies]
crossterm = { version = "0.27.0", default-features = false, features = ["bracketed-paste", "events"] }
libc = "0.2.155"
seccompiler = "0.4.0"
nix = { version = "0.29.0", features = ["process"] }
toml-span = { version = "0.3.0", features = ["reporting"] }
codespan-reporting = "0.11.1"
derive_more = { version = "0.99.18", default-features = false, features = ["from", "display"] }
clap = { version = "4.5.13", features = ["derive"] }
