[package]
name = "skeld"
version = "0.3.0-dev"
edition = "2021"
rust-version = "1.81"

authors = ["hacrvlq <hacrvlq@proton.me"]
description = "a tui tool for opening projects in a restricted sandbox to prevent supply chain attacks such as typesquatting"
keywords = ["sandbox", "security", "project", "tui", "terminal-interface"]
categories = ["command-line-interface"]
readme = "docs/README.md"
repository = "https://github.com/hacrvlq/skeld"
documentation = "https://github.com/hacrvlq/skeld/blob/v0.3.0/docs/DOCS.md"
license = "MIT"

[profile.release]
lto = true
codegen-units = 1
strip = true

[dependencies]
crossterm = { version = "0.28.1", default-features = false, features = ["bracketed-paste", "events"] }
libc = "0.2.155"
seccompiler = "0.4.0"
nix = { version = "0.29.0", features = ["process"] }
toml-span = { version = "0.3.0", features = ["reporting"] }
codespan-reporting = "0.11.1"
derive_more = { version = "1.0.0", features = ["from", "display"] }
clap = { version = "4.5.13", features = ["derive"] }
